### ISSUE TITLE
Error while running java -Dfile.encoding=utf-8 -jar foxtrot-server/target/foxtrot-server-0.1.jar initialize config/local.yml

### ISSUE THREAD

**Issue by shekhar-novo** [Flipkart/foxtrot#45]
Hi,
I'm getting following error while setting up foxtrot.  I have cloned the repo and ran "mvn clean install" command. I'm currently using Java 8.

Shekhars-MacBook-Pro:foxtrot shekhargupta$ java -Dfile.encoding=utf-8 -jar foxtrot-server/target/foxtrot-server-0.1.jar initialize config/local.yml
15/11/02 12:12:34 INFO util.Version: HV000001: Hibernate Validator 4.3.1.Final
INFO  [2015-11-02 06:42:35,122] ElasticsearchConnection: Starting Elasticsearch Client
15/11/02 12:12:35 INFO elasticsearch.plugins: [Doctor Droom] loaded [], sites []
INFO  [2015-11-02 06:42:35,846] ElasticsearchConnection: Added Elasticsearch Node : localhost
INFO  [2015-11-02 06:42:35,846] ElasticsearchConnection: Started Elasticsearch Client
Exception in thread "main" org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: []
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:305)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:200)
	at org.elasticsearch.client.transport.support.InternalTransportClusterAdminClient.execute(InternalTransportClusterAdminClient.java:86)
	at org.elasticsearch.client.support.AbstractClusterAdminClient.health(AbstractClusterAdminClient.java:127)
	at org.elasticsearch.action.admin.cluster.health.ClusterHealthRequestBuilder.doExecute(ClusterHealthRequestBuilder.java:92)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:91)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:65)
	at com.flipkart.foxtrot.server.InitializerCommand.run(InitializerCommand.java:122)
	at com.flipkart.foxtrot.server.InitializerCommand.run(InitializerCommand.java:36)
	at com.yammer.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:58)
	at com.yammer.dropwizard.cli.Cli.run(Cli.java:53)
	at com.yammer.dropwizard.Service.run(Service.java:61)
	at com.flipkart.foxtrot.server.App.main(App.java:30)

**Comment by shekhar-novo** [comment]
I ignored the instructions that elastic search and HBase should be installed on system. Hence closing this  issue
